apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:

- servicemeshpeers.yml

# Change to importedserviceset.yml if target traffic pattern is:  mirror or server-side load-balancing
#- importedserviceset.yml
- importedserviceset-failover.yml
