# Joins two meshes together
kind: ServiceMeshPeer
apiVersion: federation.maistra.io/v1
metadata:

  # Name will be used to identify the cluster to which imported services belong
  name: east2

  namespace: east-istio-system
spec:

  remote:
    addresses:
    #- 192.168.1.202
    - ingress-east.east2-istio-system.svc.cluster.local
    discoveryPort: 8188
    servicePort: 15443

  gateways:
    ingress:
      name: ingress-east2
    egress:
      name: egress-east2
  security:
    trustDomain: east2.local

    # The "clientID" field is used to identify the service account that will be used to authenticate the peer ( when it communicates with other services in the service mesh )
    clientID: east2.local/ns/east2-istio-system/sa/egress-east-service-account

    certificateChain:
      kind: ConfigMap
      name: east2-ca-root-cert
