kind: ExportedServiceSet
apiVersion: federation.maistra.io/v1
metadata:
 # The name of the ExportedServiceSet must match the ServiceMeshPeer name
 name: east

 namespace: west-istio-system
spec:
 exportRules:
 - type: LabelSelector
   labelSelector:
     namespace: west-mesh-member
     selector:
       matchLabels:
         app.kubernetes.io/name: kube-info
     alias:
       namespace: east-mesh-member
