# Joins two meshes together
kind: ServiceMeshPeer
apiVersion: federation.maistra.io/v1
metadata:
  name: east
  namespace: west-istio-system
spec:

  remote:
    addresses:
    - a218d34ddf77b47a4af651a3caf8d7a0-372390872.us-east-2.elb.amazonaws.com  # $WEST_LB This value comes from namespace: east-istio-system -> service/ingress-west
    discoveryPort: 8188
    servicePort: 15443
    
  gateways:
    ingress:
      name: ingress-east
    egress:
      name: egress-east
  security:
    trustDomain: east.local

    # The "clientID" field is used to identify the service account that will be used to authenticate the peer ( when it communicates with other services in the service mesh )
    clientID: east.local/ns/east-istio-system/sa/egress-west-service-account

    certificateChain:
      kind: ConfigMap
      name: east-ca-root-cert
